library(data.table)
map = fread("map.txt")
data = fread("data.txt")
map = unlist(map)
data = unlist(data)
map.data = data.frame(map = map, data = data)
map.data = subset(map.data, !(is.na(map) & is.na(data)) & map != "")
fwrite(map.data, file = "mapped_data.tsv", sep = "\t")
